export interface User {
    id: number;
    name: string;
    address: string;
}

export const Users: User[] = [
    { id: 1, name: 'Аншанц Ксения Станиславовна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 31' },
    { id: 2, name: 'Ахметжанов Ильяс Умярович', address: 'г Москва, ул Кошкина, д 11 к 1, кв 32' },
    { id: 3, name: 'Бильданова Арина Радиевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 33' },
    { id: 4, name: 'Верзунова Евгения Алексеевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 34' },
    { id: 5, name: 'Глухов Александр Андреевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 35' },
    { id: 6, name: 'Жарков Александр Дмитриевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 36' },
    { id: 7, name: 'Казакова Елизавета Александровна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 37' },
    { id: 8, name: 'Ковалюсь Игорь Олегович', address: 'г Москва, ул Кошкина, д 11 к 1, кв 38' },
    { id: 9, name: 'Красникова Валерия Евгеньевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 39' },
    { id: 10, name: 'Кучина Екатерина Юрьевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 40' },
    { id: 11, name: 'Кушнарева Елизавета Максимовна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 41' },
    { id: 12, name: 'Морозов Илья Андреевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 42' },
    { id: 13, name: 'Муравьева Елизавета Юрьевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 43' },
    { id: 14, name: 'Никулушкин Максим Алексеевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 44' },
    { id: 15, name: 'Панкратова Жанна Борисовна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 45' },
    { id: 16, name: 'Платовская Валентина Сергеевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 46' },
    { id: 17, name: 'Потёмкин Григорий Анатольевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 47' },
    { id: 18, name: 'Титов Михаил Андреевич', address: 'г Москва, ул Кошкина, д 11 к 1, кв 48' },
    { id: 19, name: 'Топада Злата Валерьевна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 49' },
    { id: 20, name: 'Федорова Дарья Александровна', address: 'г Москва, ул Кошкина, д 11 к 1, кв 50' },
    { id: 21, name: 'Чурбанов Константин Иванович', address: 'г Москва, ул Кошкина, д 11 к 1, кв 51' },
    { id: 22, name: 'Юсибов Эльнур Эльшад оглы', address: 'г Москва, ул Кошкина, д 11 к 1, кв 52' },
    { id: 23, name: 'Яковишин Евгений Вячеславович', address: 'г Москва, ул Кошкина, д 11 к 1, кв 53' },
    { id: 24, name: 'Ахремова Анна Игоревна', address: 'г Москва, Пролетарский пр., д 8 к 2, кв 84' },
    { id: 25, name: 'Гапанович Валентин Михайлович', address: 'г Москва, Пролетарский пр., д 8 к 2, кв 85' },
    { id: 26, name: 'Зарецкая Дарья Олеговна', address: 'г Москва, Пролетарский пр., д 8 к 2, кв 86' },
    { id: 27, name: 'Чолак Владислав Дмитриевич', address: 'г Москва, Пролетарский пр., д 8 к 2, кв 87' },
    { id: 28, name: 'Ширитон Серафим Александрович', address: 'г Москва, Пролетарский пр., д 8 к 2, кв 88' },
    { id: 29, name: '', address: '' },
    { id: 30, name: '', address: '' },
    { id: 31, name: '', address: '' },
    { id: 32, name: '', address: '' },
    { id: 33, name: '', address: '' },
    { id: 34, name: '', address: '' },
    { id: 35, name: '', address: '' },
    { id: 36, name: '', address: '' },
    { id: 37, name: '', address: '' },
    { id: 38, name: '', address: '' },
    { id: 39, name: '', address: '' },
    { id: 40, name: '', address: '' },
    { id: 41, name: '', address: '' },
    { id: 42, name: '', address: '' },
    { id: 43, name: '', address: '' },
    { id: 44, name: '', address: '' },
    { id: 45, name: '', address: '' },
    { id: 46, name: '', address: '' },
    { id: 47, name: '', address: '' },
    { id: 48, name: '', address: '' },
    { id: 49, name: '', address: '' },
    { id: 50, name: '', address: '' },
    { id: 51, name: '', address: '' },
    { id: 52, name: '', address: '' },
    { id: 53, name: '', address: '' },
    { id: 54, name: '', address: '' },
    { id: 55, name: '', address: '' },
    { id: 56, name: '', address: '' },
    { id: 57, name: '', address: '' },
    { id: 58, name: '', address: '' },
    { id: 59, name: '', address: '' },
    { id: 60, name: '', address: '' },
    { id: 61, name: '', address: '' },
    { id: 62, name: '', address: '' },
    { id: 63, name: '', address: '' },
    { id: 64, name: '', address: '' },
    { id: 65, name: '', address: '' },
    { id: 66, name: '', address: '' },
    { id: 67, name: '', address: '' },
    { id: 68, name: '', address: '' },
    { id: 69, name: '', address: '' },
    { id: 70, name: '', address: '' },
    { id: 71, name: '', address: '' },
    { id: 72, name: '', address: '' },
    { id: 73, name: '', address: '' },
    { id: 74, name: '', address: '' },
    { id: 75, name: '', address: '' },
    { id: 76, name: '', address: '' },
    { id: 77, name: '', address: '' },
    { id: 78, name: '', address: '' },
    { id: 79, name: '', address: '' },
    { id: 80, name: '', address: '' },
    { id: 81, name: '', address: '' },
    { id: 82, name: '', address: '' },
    { id: 83, name: '', address: '' },
    { id: 84, name: '', address: '' },
    { id: 85, name: '', address: '' },
    { id: 86, name: '', address: '' },
    { id: 87, name: '', address: '' },
    { id: 88, name: '', address: '' },
    { id: 89, name: '', address: '' },
    { id: 90, name: '', address: '' },
    { id: 91, name: '', address: '' },
    { id: 92, name: '', address: '' },
    { id: 93, name: '', address: '' },
    { id: 94, name: '', address: '' },
    { id: 95, name: '', address: '' },
    { id: 96, name: '', address: '' },
    { id: 97, name: '', address: '' },
    { id: 98, name: '', address: '' },
    { id: 99, name: '', address: '' },
    { id: 100, name: '', address: '' }
];

